"""empty message

Revision ID: 2e718997586a
Revises: None
Create Date: 2016-02-04 16:05:31.219979

"""

# revision identifiers, used by Alembic.
revision = '2e718997586a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    ### end Alembic commands ###
